version: '3'
services:
  nuxtdev:
    build: 
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    expose:
      "3000"
        #environment:
        #  PORT: 3000
        #  HOST: 0.0.0.0  
